name: XCResultz
description: Parse an xcresults and generate a summary.
author: GitHub Actions

# Define your inputs here.
inputs:
  path:
    description: Path to xcresults
    required: true
    default: Test.xcresults

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ github.action_path }}
        swift run Keanu \
          --path ${{ inputs.path }} \
          --working-directory ${{ github.workspace }}
      shell: bash

    - name: Step Summary
      run: echo 'Hello world!' >> $GITHUB_STEP_SUMMARY
      shell: bash
