name: Hello, World!
description: Greet someone and record the time
author: GitHub Actions

# Define your inputs here.
inputs:
  target:
    description: Target
    required: true
    default: Keanu
  product:
    description: Product
    required: true
    default: Keanu

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ github.action_path }}
        swift run Keanu \
          --target ${{ inputs.target }} \
          --product ${{ inputs.product }} \
          --working-directory ${{ github.workspace }}
      shell: bash
